name = "Vanilla Ish — 26.3 Test"
author = "Logan"
version = "1.1.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b1438df902d52ca6861298ec223728f9eb2328b7e29f8f322d282590d5d8bb2"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
datapack-folder = "datapacks"
