name = "Vanilla Ish"
author = "Logan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "628c1347ebfde13045284897fa645f90a5c5c5e1860095f1780bb13f88b21ce8"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
