name = "Vanilla Ish"
author = "Logan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b36d05073e1fb34dcc6216a75152abb9f7a431a74772c829668445d5f09e901a"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
