name = "Vanilla Ish"
author = "Logan"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "792b7ea253855a6afedf25f39ed3f95ddb09dbed27e5a2215ccd42b8fbc9c60e"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
